# Name of your workflow that will be displayed in GitHub Actions
name: CI Demo

# When should the workflow run
on:
  push:
    branches:
      - main
  pull_request:

# What work should be done
jobs:  
  demo-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run command
      - name: Run a one-line script
        run: echo "CI is running"